# Generated by Django 3.2.2 on 2021-06-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toy', '0003_auto_20210610_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tour',
            },
        ),
    ]
