# Generated by Django 3.2.2 on 2021-06-24 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toy', '0005_auto_20210624_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usrs',
            old_name='name',
            new_name='place',
        ),
        migrations.RemoveField(
            model_name='usrs',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usrs',
            name='pwd',
        ),
    ]
