# Generated by Django 3.2.3 on 2021-06-27 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toy', '0007_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='sem',
            new_name='days',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='usn',
        ),
        migrations.AddField(
            model_name='contact',
            name='persons',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
