# Generated by Django 3.2.2 on 2021-06-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toy', '0008_auto_20210627_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(default='', max_length=50)),
                ('pswd', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
